version: '3.1'

services:

  wordpress:
    build:
      dockerfile: ./Docker/wp.Dockerfile
    restart: always
    environment:
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG}
      WORDPRESS_DB_HOST: db
      WORDPRESS_DB_USER: ${SQLDATABASE_USER_NAME}
      WORDPRESS_DB_PASSWORD: ${SQLDATABASE_USER_PASSWORD}
      WORDPRESS_DB_NAME: ${SQLDATABASE_DB_NAME}
      WORDPRESS_TABLE_PREFIX: ${WORDPRESS_TABLE_PREFIX}
      WORDPRESS_AUTH_KEY: ${WORDPRESS_AUTH_KEY}
      WORDPRESS_SECURE_KEY: ${WORDPRESS_SECURE_KEY}
      WORDPRESS_LOGGED_IN_KEY: ${WORDPRESS_LOGGED_IN_KEY}
      WORDPRESS_NONCE_KEY: ${WORDPRESS_NONCE_KEY}
      WORDPRESS_SECURE_AUTH_SALT: ${WORDPRESS_SECURE_AUTH_SALT}
      WORDPRESS_LOGGED_IN_SALT: ${WORDPRESS_LOGGED_IN_SALT}
      WORDPRESS_NONCE_SALT: ${WORDPRESS_NONCE_SALT}

      # our local dev environment
      WORDPRESS_CONFIG_EXTRA: |
        /* development parameters */
        define('WP_CACHE', false);
        define('ENVIRONMENT', 'local');
        /* do not re-define WP_DEBUG here or it will throw a blank error in the admin */
        /* you can remove this entirely, this is just to show you what not to do */
        // define('WP_DEBUG', true);
        if (!defined('WP_HOME')) {
          /* force our home url */
          define('WP_HOME', 'http://test.local');
          define('WP_SITEURL', WP_HOME);
        }
        define( 'WP_DEBUG_LOG', true ); 
    volumes:
      - wordpress:/var/www/html
      - ./themes/yourtheme:/var/www/html/wp-content/themes/yourtheme:delegate
      - ./plugins:/var/www/html/wp-content/plugins/
      - ./mu-plugins:/var/www/html/wp-content/mu-plugins
      - ./uploads:/var/www/html/wp-content/uploads
      - ./logs:/var/www/html/wp-content/logs
      - ./uploads.ini:/usr/local/etc/php/conf.d/uploads.ini
      - ./error-logging.ini:/usr/local/etc/php/conf.d/error-logging.ini
    networks:
      - wordpress

  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: ${SQLDATABASE_DB_NAME}
      MYSQL_USER: ${SQLDATABASE_USER_NAME}
      MYSQL_PASSWORD: ${SQLDATABASE_USER_PASSWORD}
      MYSQL_RANDOM_ROOT_PASSWORD: ${SQLDATABASE_ROOT_PASSWORD}
    volumes:
      - db:/var/lib/mysql
    networks:
      - wordpress

volumes:
  wordpress:
  db:
  backwpup:

networks:
  wordpress:
    ipam:
      config:
        - subnet: 172.25.0.0/16
